-- ***************************** SqlDBM: MySQL ****************************
-- * Generated by SqlDBM:  Project-1, v19 by raghav.gupta@zemosolabs.com *

create database hotel;
use hotel;


-- ************************************** `Customer`

CREATE TABLE `Customer`
(
 `CustID` numeric NOT NULL ,
 `Name`   varchar(45) NOT NULL ,
 `Age`    varchar(45) NOT NULL ,
 `Phone`  numeric(10) NOT NULL ,
 `Email`  varchar(45) NULL ,

PRIMARY KEY (`CustID`)
);





CREATE TABLE `Hotel`
(
 `HotelID`      int NOT NULL ,
 `HotelName`    varchar(45) NOT NULL ,
 `TotalRooms`   numeric NOT NULL ,
 `Desciription` varchar(45) NOT NULL ,
 `City`         varchar(45) NOT NULL ,

PRIMARY KEY (`HotelID`)
);






CREATE TABLE `Room`
(
 `RoomID`   int NOT NULL ,
 `Floor_No` int NOT NULL ,
 `HotelID`  int NOT NULL ,
 `Price`    decimal(10,2) NOT NULL ,

PRIMARY KEY (`RoomID`),
KEY `FK_63` (`HotelID`),
CONSTRAINT `FK_61` FOREIGN KEY `FK_63` (`HotelID`) REFERENCES `Hotel` (`HotelID`)
);




CREATE TABLE `Booking`
(
 `HotelID`      int NOT NULL ,
 `CheckInDate`  date NOT NULL ,
 `CustID`       numeric NOT NULL ,
 `CheckOutDate` date NOT NULL ,
 `BookingID`    int NOT NULL ,

PRIMARY KEY (`HotelID`),
KEY `FK_56` (`HotelID`),
CONSTRAINT `FK_54` FOREIGN KEY `FK_56` (`HotelID`) REFERENCES `Hotel` (`HotelID`),
KEY `FK_81` (`CustID`),
CONSTRAINT `FK_79` FOREIGN KEY `FK_81` (`CustID`) REFERENCES `Customer` (`CustID`)
);




